### ISSUE TITLE
The wrong status code is returned when there is an error

### ISSUE THREAD

**Issue by duganchen** [cglindkamp/run-mailcap-rs#4]
If I do "run-mailcap-rs aaaa" when "aaaa" is not a file that exists, then run-mailcap-rs just returns zero to the OS, printing nothing.

This is what the original mailcap program does:

    $ ./run-mailcap aaaa
    Error: no such file "aaaa"
    $ echo $?
    2

**Comment by cglindkamp** [comment]
Thanks for the report. There are definately some shortcomings regardings error handling, especially concerning the exit code. I already did some work on that, but it may take a while until I have something, that I can push.

**Comment by cglindkamp** [comment]
I just pushed a commit, that should solve your problem. The exit codes might not 100% match those of the original run-mailcap, but if the numbers itself do not matter, this might be sufficient for you.
