### ISSUE TITLE
cannot handle file names with spaces.

### ISSUE THREAD

**Issue by ghost** [cglindkamp/run-mailcap-rs#5]
[~/files]$ feh '2017 02-14-03.16.10_2.jpg'
[~/files]$ run-mailcap '2017 02-14-03.16.10_2.jpg'
feh WARNING: 2017 does not exist - skipping
feh WARNING: 02-14-03.16.10_2.jpg does not exist - skipping
feh: No loadable images specified.
See 'man feh' for detailed usage information
[~/files]$

**Comment by cglindkamp** [comment]
This should work if you put quotes into your .mailcap file:
```
image/jpeg; feh '%s'
```

**Comment by ghost** [comment]
you are right, thank you.
